In [20]:
import sqlite3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [21]:
conn = sqlite3.connect('olist.db')

In [22]:
try:
    df = pd.read_csv('archive/olist_customers_dataset.csv')
    df.to_sql('customers', conn, index=False)
    df = pd.read_csv('archive/olist_orders_dataset.csv')
    df.to_sql('orders', conn, index=False)
    df = pd.read_csv('archive/olist_order_items_dataset.csv')
    df.to_sql('order_items', conn, index=False)
    df = pd.read_csv('archive/olist_order_payments_dataset.csv')
    df.to_sql('order_payments', conn, index=False)
    df = pd.read_csv('archive/olist_order_reviews_dataset.csv')
    df.to_sql('order_reviews', conn, index=False)
    df = pd.read_csv('archive/olist_products_dataset.csv')
    df.to_sql('products', conn, index=False)
    df = pd.read_csv('archive/olist_sellers_dataset.csv')
    df.to_sql('sellers', conn, index=False)
    df = pd.read_csv('archive/olist_geolocation_dataset.csv')
    df.to_sql('geolocation', conn, index=False)
except Exception as e:
    print(e)

Table 'customers' already exists.

In [23]:
pd.read_sql_query('SELECT * FROM customers', conn).head(10)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
5,879864dab9bc3047522c92c82e1212b8,4c93744516667ad3b8f1fb645a3116a4,89254,jaragua do sul,SC
6,fd826e7cf63160e536e0908c76c3f441,addec96d2e059c80c30fe6871d30d177,4534,sao paulo,SP
7,5e274e7a0c3809e14aba7ad5aae0d407,57b2a98a409812fe9618067b6b8ebe4f,35182,timoteo,MG
8,5adf08e34b2e993982a47070956c5c65,1175e95fb47ddff9de6b2b06188f7e0d,81560,curitiba,PR
9,4b7139f34592b3a31687243a302fa75b,9afe194fb833f79e300e37e580171f22,30575,belo horizonte,MG

In [24]:
pd.read_sql_query('SELECT * FROM orders', conn).head(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07 00:00:00
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06 00:00:00
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00

In [25]:
pd.read_sql_query('SELECT * FROM order_payments', conn).head(10)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
5,298fcdf1f73eb413e4d26d01b25bc1cd,1,credit_card,2,96.12
6,771ee386b001f06208a7419e4fc1bbd7,1,credit_card,1,81.16
7,3d7239c394a212faae122962df514ac7,1,credit_card,3,51.84
8,1f78449c87a54faf9e96e88ba1491fa9,1,credit_card,6,341.09
9,0573b5e23cbd798006520e1d5b4c6714,1,boleto,1,51.95

In [26]:
Query = """SELECT SUM(payment_value) AS total_revenue,order_status FROM order_payments JOIN orders
            ON orders.order_id = order_payments.order_id
            GROUP BY order_status
            ORDER BY SUM(payment_value) DESC
        """
pd.read_sql_query(Query, conn).head()

   total_revenue order_status
0    15422461.77    delivered
1      177213.96      shipped
2      143255.60     canceled
3      126479.51  unavailable
4       69394.11   processing

In [27]:
Query = """SELECT MIN(order_purchase_timestamp) AS min_date,
           MAX(order_purchase_timestamp) AS max_date
           FROM orders
        """
pd.read_sql_query(Query, conn).head()

              min_date             max_date
0  2016-09-04 21:15:19  2018-10-17 17:30:18

In [28]:
Query = """SELECT customers.customer_unique_id , orders.order_id , orders.order_purchase_timestamp , order_payments.payment_value
           FROM orders
           JOIN customers
                ON orders.customer_id = customers.customer_id
           JOIN order_payments
                ON orders.order_id = order_payments.order_id
           WHERE order_status = 'delivered'
        """
rfm_df = pd.read_sql_query(Query, conn)
rfm_df.head()

,customer_unique_id,order_id,order_purchase_timestamp,payment_value
0,7c396fd4830fd04220f754e42b4e5bff,e481f51cbdc54678b7cc49136f2d6af7,2017-10-02 10:56:33,2.00
1,7c396fd4830fd04220f754e42b4e5bff,e481f51cbdc54678b7cc49136f2d6af7,2017-10-02 10:56:33,18.12
2,7c396fd4830fd04220f754e42b4e5bff,e481f51cbdc54678b7cc49136f2d6af7,2017-10-02 10:56:33,18.59
3,af07308b275d755c9edb36a90c618231,53cdb2fc8bc7dce0b6741e2150273451,2018-07-24 20:41:37,141.46
4,3a653a41f6f9fc3d2a113cf8398680e8,47770eb9100c2d0c44946d9cf07ec65d,2018-08-08 08:38:49,179.12

In [29]:
rfm_df['order_purchase_timestamp'] = pd.to_datetime(rfm_df['order_purchase_timestamp'])

rfm_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100756 entries, 0 to 100755
Data columns (total 4 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   customer_unique_id        100756 non-null  str
 1   order_id                  100756 non-null  str
 2   order_purchase_timestamp  100756 non-null  datetime64[us]
 3   payment_value             100756 non-null  float64
dtypes: datetime64[us](1), float64(1), str(2)
memory usage: 9.2 MB

In [30]:
snapshot_date = rfm_df['order_purchase_timestamp'].max() + pd.Timedelta(days=1)
snapshot_date

Timestamp('2018-08-30 15:00:37')

In [31]:
rfm = rfm_df.groupby('customer_unique_id').agg({
    'order_purchase_timestamp': 'max',
    'order_id': 'nunique',
    'payment_value': 'sum'
})
rfm

,order_purchase_timestamp,order_id,payment_value
customer_unique_id,,,
0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10 10:56:27,1,141.90
0000b849f77a49e4a4ce2b2a4ca5be3f,2018-05-07 11:11:27,1,27.19
0000f46a3911fa3c0805444483337064,2017-03-10 21:05:03,1,86.22
0000f6ccb0745a6a4b88665a16c9f078,2017-10-12 20:29:41,1,43.62
0004aac84e0df4da2b147fca70cf8255,2017-11-14 19:45:42,1,196.89
...,...,...,...
fffcf5a5ff07b0908bd4e2dbc735a684,2017-06-08 21:00:36,1,2067.42
fffea47cd6d3cc0a88bd621562a9d061,2017-12-10 20:07:56,1,84.58
ffff371b4d645b6ecea244b27531430a,2017-02-07 15:49:16,1,112.46
ffff5962728ec6157033ef9805bacc48,2018-05-02 15:17:41,1,133.69
ffffd2657e2aad2907e67c3e9daecbeb,2017-05-02 20:18:45,1,71.56

In [32]:
rfm['recency'] = (snapshot_date - rfm['order_purchase_timestamp']).dt.days
rfm.rename(columns={'order_id': 'frequency' , 'payment_value': 'monetary'}, inplace=True)
rfm = rfm[['recency', 'frequency', 'monetary']]
rfm

                                  recency  frequency  monetary
customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2      112          1    141.90
0000b849f77a49e4a4ce2b2a4ca5be3f      115          1     27.19
0000f46a3911fa3c0805444483337064      537          1     86.22
0000f6ccb0745a6a4b88665a16c9f078      321          1     43.62
0004aac84e0df4da2b147fca70cf8255      288          1    196.89
...                                   ...        ...       ...
fffcf5a5ff07b0908bd4e2dbc735a684      447          1   2067.42
fffea47cd6d3cc0a88bd621562a9d061      262          1     84.58
ffff371b4d645b6ecea244b27531430a      568          1    112.46
ffff5962728ec6157033ef9805bacc48      119          1    133.69
ffffd2657e2aad2907e67c3e9daecbeb      484          1     71.56

[93357 rows x 3 columns]

In [33]:
rfm.quantile(q=[0.2, 0.4, 0.6, 0.8, 1.0])
rfm['R_Score'] = pd.qcut(rfm['recency'], q=5, labels=[5, 4, 3, 2, 1])
rfm['F_Score'] = pd.qcut(rfm['frequency'].rank(method='first'), q=5, labels=[1, 2, 3, 4, 5])
rfm['M_Score'] = pd.qcut(rfm['monetary'], q=5, labels=[1, 2, 3, 4, 5])
rfm.head()

,recency,frequency,monetary,R_Score,F_Score,M_Score
customer_unique_id,,,,,,
0000366f3b9a7992bf8c76cfdf3221e2,112,1,141.90,4,1,4
0000b849f77a49e4a4ce2b2a4ca5be3f,115,1,27.19,4,1,1
0000f46a3911fa3c0805444483337064,537,1,86.22,1,1,2
0000f6ccb0745a6a4b88665a16c9f078,321,1,43.62,2,1,1
0004aac84e0df4da2b147fca70cf8255,288,1,196.89,2,1,4

In [34]:
rfm['rfm_segment'] = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str) + rfm['M_Score'].astype(str)
rfm.head()
rfm['rfm_score_total'] = rfm['R_Score'].astype(int) + rfm['F_Score'].astype(int) + rfm['M_Score'].astype(int)
rfm.head()

,recency,frequency,monetary,R_Score,F_Score,M_Score,rfm_segment,rfm_score_total
customer_unique_id,,,,,,,,
0000366f3b9a7992bf8c76cfdf3221e2,112,1,141.90,4,1,4,414,9
0000b849f77a49e4a4ce2b2a4ca5be3f,115,1,27.19,4,1,1,411,6
0000f46a3911fa3c0805444483337064,537,1,86.22,1,1,2,112,4
0000f6ccb0745a6a4b88665a16c9f078,321,1,43.62,2,1,1,211,4
0004aac84e0df4da2b147fca70cf8255,288,1,196.89,2,1,4,214,7

In [ ]:
def get_rfm_segment(rfm_score_total):
    if rfm_score_total <= 3:
        return 'Lost'
    elif rfm_score_total <= 6:
        return 'At Risk'
    elif rfm_score_total <= 9:
        return 'Potential Loyalists'
    elif rfm_score_total <= 12:
        return 'Loyal Customers'
    elif rfm_score_total <= 15:
        return 'VIP'
    else:
        return 'not provided'

rfm['Customer_Profile'] = rfm['rfm_score_total'].apply(get_rfm_segment)
rfm.head()

,recency,frequency,monetary,R_Score,F_Score,M_Score,rfm_segment,rfm_score_total,Customer_Profile
customer_unique_id,,,,,,,,,
0000366f3b9a7992bf8c76cfdf3221e2,112,1,141.90,4,1,4,414,9,Potential Loyalists
0000b849f77a49e4a4ce2b2a4ca5be3f,115,1,27.19,4,1,1,411,6,At Risk
0000f46a3911fa3c0805444483337064,537,1,86.22,1,1,2,112,4,At Risk
0000f6ccb0745a6a4b88665a16c9f078,321,1,43.62,2,1,1,211,4,At Risk
0004aac84e0df4da2b147fca70cf8255,288,1,196.89,2,1,4,214,7,Potential Loyalists